// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-Veop8rp46PPsy_1dgShKyFdCQeHMBQ',
    appId: '1:102893875087:web:e11953338f91225387e5fa',
    messagingSenderId: '102893875087',
    projectId: 'pampadycathedral1',
    authDomain: 'pampadycathedral1.firebaseapp.com',
    storageBucket: 'pampadycathedral1.appspot.com',
    measurementId: 'G-11S4B8V4ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSk3b298F6oeZOhX3GBrmwNIoWpZ1p6Y',
    appId: '1:102893875087:android:7389711b091d15ee87e5fa',
    messagingSenderId: '102893875087',
    projectId: 'pampadycathedral1',
    storageBucket: 'pampadycathedral1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJ-hh0lOlVAq9jUYt_ZOvn5HqDxRKscA',
    appId: '1:102893875087:ios:8e54b34c4ed2a6fe87e5fa',
    messagingSenderId: '102893875087',
    projectId: 'pampadycathedral1',
    storageBucket: 'pampadycathedral1.appspot.com',
    iosClientId: '102893875087-ubd3m91v35827ckbsnb6duqq6u7f81b0.apps.googleusercontent.com',
    iosBundleId: 'com.tvek.pampadycathedral',
  );
}
